services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    restart: always
    ports:
      - "80:80" #HTTP
      - "81:81" #Adminsitracion de la api
      - "443:443" #HTTPS
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    depends_on:
      - app-backend
    networks:
      - red-nico


  servidor-bd:
    image: mysql:latest
    container_name: servidor-bdNico
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    networks:
      - red-nico

  app-backend:
    build: ./backend
    container_name: app-backend
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - servidor-bd
    networks:
      - red-nico

networks:
  red-nico:
    driver: bridge